/**
 * Auto-generated TypeScript types from supabase schema.
 * Generated by scripts/types-from-schema.py — DO NOT EDIT MANUALLY
 * To regenerate, run: python3 scripts/types-from-schema.py
 */

// ============================================================================
// Table Types
// ============================================================================

export interface AcademyAccess {
  expiresAt: string | null;
  stage: number;
  updatedAt: string;
  userId: string | null;
}

export interface AcademyProgress {
  completed: boolean | null;
  createdAt: string | null;
  id: string | null;
  nodeId: string | null;
  userId: string | null;
  xpAwarded: number | null;
}

export interface AccessAudit {
  action: string;
  actorId: string | null;
  createdAt: string;
  id: number | null;
  next: Record<string, any> | null;
  prev: Record<string, any> | null;
  subjectId: string;
}

export interface AccessGrantAudit {
  action: string;
  actorUid: string | null;
  allowed: boolean;
  detail: string | null;
  id: any | null;
  occurredAt: string;
  targetUid: string | null;
}

export interface ActivityFeed {
  activityType: string;
  body: string | null;
  createdAt: string;
  id: string | null;
  isPublic: boolean;
  likesCount: number;
  metadata: Record<string, any> | null;
  title: string;
}

export interface Advertisements {
  category: string | null;
  company: string;
  contactEmail: string;
  createdAt: string | null;
  description: string | null;
  endsAt: string | null;
  id: string | null;
  rateTier: string | null;
  startsAt: string | null;
  status: string | null;
  title: string;
  url: string | null;
}

export interface AgentThreads {
  agentName: string;
  createdAt: string;
  id: string | null;
  lastQuery: string | null;
  lastResponse: string | null;
  messageCount: number | null;
  messages: Record<string, any>;
  summary: string | null;
  threadId: string;
  updatedAt: string;
}

export interface AiMemory {
  agentName: string | null;
  content: string;
  createdAt: string;
  expiresAt: string | null;
  id: string | null;
  memoryKey: string | null;
  memoryType: string | null;
  source: string | null;
  updatedAt: string | null;
  userId: string | null;
}

export interface ApiKeys {
  createdAt: string;
  expiresAt: string | null;
  id: string | null;
  isActive: boolean | null;
  keyHash: string;
  keyName: string;
  keyPrefix: string;
  keyType: string;
  lastUsedAt: string | null;
  rateLimitRpm: number | null;
  requestsToday: number | null;
  requestsTotal: number | null;
}

export interface AutomationRules {
  createdAt: string;
  id: string | null;
  isOn: boolean | null;
  triggerKey: string;
  userId: string | null;
}

export interface BloodlineNodes {
  createdAt: string | null;
  id: string | null;
  name: string;
  userId: string | null;
}

export interface CapabilityKpiLog {
  id: string | null;
  kpiName: string;
  measuredAt: string;
}

export interface CapabilityRegistry {
  capabilityId: string;
  capabilityName: string;
  createdAt: string;
  description: string | null;
  domain: string;
  healthStatus: string;
  id: string | null;
  lastDeployed: string | null;
  lifecycleStatus: string;
  ownerAgent: string;
  retirementPolicy: string | null;
  sloP95Ms: number | null;
  threatModel: string | null;
  updatedAt: string;
  version: string;
}

export interface Certificates {
  certNum: number | null;
  id: string | null;
  issuedAt: string | null;
  milestone: string | null;
  title: string | null;
  userId: string | null;
}

export interface CharacterRecords {
  dominantTrait: string | null;
  name: string | null;
  updatedAt: string;
  userId: string | null;
}

export interface CircuitBreakers {
  failureCount: number;
  lastFailure: string | null;
  openedAt: string | null;
  recoveryAt: string | null;
  serviceName: string | null;
  state: string;
  updatedAt: string;
}

export interface ClientErrors {
  colNo: number | null;
  createdAt: string;
  id: number | null;
  kind: string | null;
  lineNo: number | null;
  message: string;
  page: string | null;
  source: string | null;
  stack: string | null;
  userAgent: string | null;
  userId: string | null;
}

export interface CodexBookmarks {
  authors: string | null;
  excerpt: string | null;
  id: string | null;
  published: string | null;
  savedAt: string;
  title: string;
  url: string;
}

export interface CommissionContracts {
  commissionRate: number | null;
  commissionValue: number | null;
  confidentialityAccepted: boolean | null;
  counterparty: string | null;
  createdAt: string;
  dealValue: number | null;
  id: string | null;
  reference: string | null;
  scope: string | null;
  status: string | null;
  terms: string | null;
  userId: string;
}

export interface ConsentRecords {
  consentType: string;
  granted: boolean;
  grantedAt: string;
  id: string | null;
  ipHash: string | null;
  revokedAt: string | null;
  userAgent: string | null;
  version: string;
}

export interface ConsultRequests {
  brief: string | null;
  commissionRate: number | null;
  confidentialityAccepted: boolean | null;
  contact: string | null;
  createdAt: string | null;
  domain: string;
  filePath: string | null;
  id: string | null;
  message: string | null;
  preferredTime: string | null;
  status: string | null;
  urgency: string | null;
  userId: string;
}

export interface ContentRecommendations {
  contentId: string;
  contentType: string;
  expiresAt: string | null;
  generatedAt: string;
  id: string | null;
  reason: string | null;
  served: boolean | null;
  userId: string | null;
}

export interface ContentVersions {
  content: Record<string, any>;
  contentKey: string;
  createdAt: string;
  id: string | null;
  isCurrent: boolean | null;
  message: string | null;
  version: number;
}

export interface ContributionLog {
  act: string | null;
  createdAt: string | null;
  id: string | null;
  userId: string | null;
}

export interface Conversations {
  createdAt: string | null;
  id: string | null;
  userId: string | null;
}

export interface CouncilDeliberations {
  completedAt: string | null;
  context: string | null;
  createdAt: string | null;
  depth: string | null;
  finalVerdict: string | null;
  id: string;
  rolesSnapshot: Record<string, any> | null;
  status: string | null;
  subject: string;
  synthesis: Record<string, any> | null;
}

export interface DailyEngagement {
  beatCount: number;
  completedAt: string | null;
  day: string;
  firstBeatAt: string | null;
  lastBeatAt: string | null;
  secondsAccumulated: number;
  userId: string;
}

export interface DataDomains {
  classification: string | null;
  createdAt: string;
  dataSteward: string | null;
  description: string | null;
  domainId: string;
  encryption: boolean | null;
  gdprRelevant: boolean | null;
  id: string | null;
  name: string;
  ownerRole: string | null;
  piiContains: boolean | null;
  retentionDays: number | null;
}

export interface DataEntities {
  createdAt: string;
  description: string | null;
  displayName: string;
  entityId: string;
  freshnessHrs: number | null;
  id: string | null;
  lastAudited: string | null;
  rowCountEst: number | null;
  tableName: string;
}

export interface DataExportRequests {
  completedAt: string | null;
  downloadUrl: string | null;
  expiresAt: string | null;
  id: string | null;
  requestedAt: string;
  status: string;
  userId: string | null;
}

export interface DataLineage {
  createdAt: string;
  id: string | null;
  isActive: boolean | null;
  relationship: string;
  transformation: string | null;
}

export interface Dispatches {
  body: string | null;
  category: string | null;
  createdAt: string | null;
  id: string | null;
  isPublished: boolean | null;
  sign: string | null;
  title: string | null;
  userId: string | null;
}

export interface EnterpriseAccounts {
  apiAccess: boolean | null;
  contactEmail: string;
  contactName: string | null;
  country: string | null;
  createdAt: string;
  currency: string | null;
  customDomain: string | null;
  dedicatedAgent: boolean | null;
  id: string | null;
  licenseEnd: string | null;
  licenseSeats: number;
  licenseStart: string;
  licenseType: string;
  notes: string | null;
  orgName: string;
  orgType: string;
  slaTier: string;
  status: string;
  updatedAt: string;
  whiteLabel: boolean | null;
}

export interface EnterpriseAudit {
  action: string;
  createdAt: string;
  id: string | null;
  ipHash: string | null;
  metadata: Record<string, any> | null;
  outcome: string | null;
  resource: string | null;
  resourceId: string | null;
}

export interface ErrorBudgetPolicy {
  id: string | null;
  lastComputed: string | null;
  status: string;
  surface: string;
}

export interface EthicsDeclarations {
  createdAt: string;
  declarationId: string;
  description: string;
  id: string | null;
  principle: string;
  status: string;
}

export interface EventRsvps {
  createdAt: string;
  eventRef: string | null;
  userId: string | null;
}

export interface EvolutionEvents {
  axis: string | null;
  id: string | null;
}

export interface ExamResults {
  certName: string | null;
  examId: string;
  id: string | null;
  passed: boolean;
  pct: number;
  score: number;
  takenAt: string;
  total: number;
  userId: string | null;
}

export interface ExpertBookings {
  createdAt: string;
  description: string | null;
  domain: string;
  durationMin: number | null;
  id: string | null;
  meetingUrl: string | null;
  notes: string | null;
  scheduledAt: string | null;
  status: string;
  title: string;
  updatedAt: string;
}

export interface FamilyNodes {
  createdAt: string | null;
  id: string | null;
  isHeir: boolean;
  name: string | null;
  relation: string;
  sign: string | null;
}

export interface FeatureFlags {
  description: string | null;
  flagId: string | null;
  flagKey: string | null;
  id: string | null;
  isEnabled: boolean | null;
  rolloutPct: number | null;
  updatedAt: string | null;
}

export interface Feedback {
  createdAt: string;
  id: string | null;
  message: string;
  page: string | null;
  rating: number | null;
  status: string;
  userId: string | null;
}

export interface FocusSessions {
  completedAt: string;
  createdAt: string;
  distractions: number;
  id: string | null;
  mode: string;
  taskName: string;
}

export interface GovernancePolicies {
  category: string;
  content: string | null;
  createdAt: string;
  description: string | null;
  id: string | null;
  lastReviewed: string | null;
  nextReview: string | null;
  ownerRole: string | null;
  policyId: string;
  reviewCycle: string | null;
  status: string;
  title: string;
  updatedAt: string;
  version: string;
}

export interface GraphEntities {
  canonicalName: string;
  description: string | null;
  displayName: string | null;
  entityType: string;
  firstSeenAt: string | null;
  id: string | null;
  lastSeenAt: string | null;
  lastUpdatedAt: string | null;
  metadata: Record<string, any> | null;
  sourceSystem: string | null;
  xPos: number | null;
  yPos: number | null;
  zCluster: number | null;
}

export interface GraphEvents {
  afterState: Record<string, any> | null;
  beforeState: Record<string, any> | null;
  changeSummary: string | null;
  eventType: string;
  id: string | null;
  occurredAt: string;
  recordedAt: string | null;
  sourceEventId: string | null;
}

export interface GraphEvidence {
  aiModelUsed: string | null;
  extractedText: string | null;
  extractionMethod: string | null;
  extractionTimestamp: string | null;
  humanVerified: boolean | null;
  id: string | null;
  reasoningNotes: string | null;
  sourceRowId: string | null;
  sourceTable: string | null;
  sourceType: string;
  sourceUrl: string | null;
}

export interface GraphRelationships {
  direction: string | null;
  establishedAt: string | null;
  id: string | null;
  lastConfirmedAt: string | null;
  properties: Record<string, any> | null;
  relationshipType: string;
  sourceSystem: string | null;
}

export interface HabitLogs {
  completed: boolean;
  createdAt: string;
  habitId: string;
  id: string | null;
  logDate: string;
}

export interface HealthLogs {
  body: number | null;
  createdAt: string;
  id: string | null;
  mind: number | null;
  total: number | null;
  userId: string | null;
}

export interface HeritageRecords {
  body: string | null;
  createdAt: string;
  id: string | null;
  title: string;
  userId: string | null;
}

export interface Incidents {
  actionItems: Record<string, any> | null;
  createdAt: string;
  id: string | null;
  impact: string | null;
  postmortem: string | null;
  resolvedAt: string | null;
  rootCause: string | null;
  severity: string;
  startedAt: string;
  status: string;
  surface: string;
  title: string;
  ttdMinutes: number | null;
  ttrMinutes: number | null;
}

export interface InterestSignals {
  axisType: string | null;
  contentId: string;
  contentType: string;
  createdAt: string | null;
  id: string | null;
  recordedAt: string;
  sessionId: string | null;
  signalType: string;
  trackId: number | null;
  weight: number;
}

export interface KnowledgeEdges {
  edgeType: string;
  id: string | null;
}

export interface KnowledgeNodes {
  createdAt: string;
  description: string | null;
  id: string | null;
  label: string;
  nodeKey: string;
  nodeType: string;
  properties: Record<string, any> | null;
}

export interface LeaderboardSnapshots {
  displayName: string | null;
  element: string | null;
  id: string | null;
  isOwner: boolean | null;
  rankElement: number | null;
  rankGlobal: number | null;
  rankTrack: number | null;
  sign: string | null;
  snapshotDate: string;
  tier: string | null;
  trackId: number | null;
}

export interface MarketplaceListings {
  createdAt: string | null;
  description: string | null;
  filePath: string | null;
  id: string | null;
  kind: string | null;
  priceOmega: number | null;
  sellerId: string | null;
  status: string | null;
  title: string | null;
}

export interface MatrixProgress {
  a: number;
  b: number;
  c: number;
  updatedAt: string;
  userId: string | null;
}

export interface MatrixTracks {
  sign: string;
  track: number | null;
}

export interface Medals {
  earnedAt: string | null;
  id: string | null;
  issuedAt: string | null;
  medalNum: number | null;
  userId: string | null;
}

export interface MediaItems {
  createdAt: string;
  description: string | null;
  durationMin: number | null;
  element: string | null;
  id: string | null;
  mediaType: string;
  olympian: string | null;
  phase: number | null;
  sortOrder: number | null;
  status: string;
  subtitle: string | null;
  thumbnailUrl: string | null;
  title: string;
  trackId: number | null;
  videoUrl: string | null;
}

export interface MediaReservations {
  createdAt: string | null;
  duration: string | null;
  filePath: string | null;
  id: string | null;
  message: string | null;
  priceOmega: number | null;
  status: string | null;
  title: string | null;
  userId: string;
  zone: string | null;
}

export interface MemberEvents {
  createdAt: string;
  id: string | null;
  title: string;
  userId: string | null;
}

export interface MemberPerks {
  perkId: string | null;
  purchasedAt: string;
  userId: string;
}

export interface MemberPosts {
  body: string;
  commentsCount: number;
  createdAt: string;
  id: string | null;
  isPinned: boolean | null;
  likesCount: number;
  postType: string;
  status: string;
  title: string | null;
  trackId: number | null;
  updatedAt: string;
  userId: string | null;
}

export interface MemberPresence {
  clientInfo: Record<string, any> | null;
  currentPage: string | null;
  isOnline: boolean;
  lastSeen: string;
  sessionStartedAt: string | null;
  userId: string | null;
}

export interface Messages {
  content: string | null;
  conversationId: string | null;
  createdAt: string | null;
  id: string | null;
  role: string | null;
  userId: string | null;
}

export interface Notifications {
  content: string | null;
  createdAt: string | null;
  id: string | null;
  message: string | null;
  notificationType: string | null;
  readAt: string | null;
  userId: string | null;
}

export interface Oaths {
  category: string;
  createdAt: string;
  hashSha256: string;
  id: string | null;
  oathText: string;
  swornAt: string;
}

export interface OkrKeyResults {
  createdAt: string;
  currentValue: number;
  id: string | null;
  startValue: number;
  targetValue: number;
  title: string;
  unit: string;
  updatedAt: string;
}

export interface OkrObjectives {
  category: string;
  createdAt: string;
  description: string | null;
  id: string | null;
  title: string;
}

export interface PlatformEvents {
  createdAt: string;
  durationS: number | null;
  eventType: string;
  id: string | null;
  metrics: Record<string, any> | null;
  osVersion: string | null;
  page: string | null;
  sessionId: string | null;
}

export interface PlatformMetrics {
  createdAt: string;
  dimensions: Record<string, any> | null;
  id: string | null;
  metricDate: string;
  metricName: string;
}

export interface PlatformOwners {
  userId: string | null;
}

export interface PlatformSettings {
  boolValue: boolean | null;
  key: string | null;
  textValue: string | null;
  updatedAt: string | null;
}

export interface PointPerks {
  id: string | null;
}

export interface PolicyEvalLog {
  context: Record<string, any> | null;
  createdAt: string;
  effect: string;
  id: string | null;
  page: string | null;
  policyId: string;
  reason: string | null;
}

export interface PolicyRules {
  condition: Record<string, any> | null;
  createdAt: string;
  description: string;
  effect: string;
  id: string | null;
  isCritical: boolean | null;
  policyId: string;
  policyType: string;
  standard: string | null;
  updatedAt: string;
}

export interface Profiles {
  accessApproved: boolean | null;
  accessRequestedAt: string | null;
  agent: string | null;
  authority: number | null;
  avatarUrl: string | null;
  axisA: number | null;
  axisB: number | null;
  axisC: number | null;
  bgColor: string | null;
  bio: string | null;
  birthDate: string | null;
  certificatesEarned: number | null;
  deactivatedAt: string | null;
  demoWatchedAt: string | null;
  displayName: string | null;
  element: string | null;
  email: string | null;
  erasureRequestedAt: string | null;
  god: string | null;
  isOwner: boolean | null;
  isPublic: boolean | null;
  isRejected: boolean | null;
  isTrial: boolean | null;
  kycDocPath: string | null;
  kycStatus: string | null;
  kycSubmittedAt: string | null;
  materialTier: string | null;
  matrixTrack: number | null;
  medalsEarned: number | null;
  nationality: string | null;
  nodesCleared: number | null;
  nodesEarned: number | null;
  pendingDeletion: string | null;
  permanentGrantedAt: string | null;
  profession: string | null;
  sign: string | null;
  stripeCustomerId: string | null;
  subscriptionPeriodEnd: string | null;
  subscriptionPeriodStart: string | null;
  subscriptionStatus: string | null;
  subscriptionTier: string | null;
  termsAccepted: boolean | null;
  termsAcceptedAt: string | null;
  token: string | null;
  trialExpiresAt: string | null;
  trialGrantedAt: string | null;
  trophiesEarned: number | null;
}

export interface Publications {
  body: string | null;
  createdAt: string | null;
  filePath: string | null;
  id: string | null;
  kind: string;
  status: string | null;
  title: string | null;
}

export interface RateLimits {
  key: string | null;
  lastRefill: string;
  tokens: number;
  updatedAt: string;
}

export interface ResearchHypotheses {
  createdAt: string;
  domain: string | null;
  id: string | null;
  userId: string | null;
}

export interface RiskRegister {
  category: string;
  createdAt: string;
  description: string | null;
  id: string | null;
  impact: number;
  iso27001Control: string | null;
  likelihood: number;
  mitigation: string | null;
  owaspRef: string | null;
  ownerRole: string | null;
  residualRisk: number | null;
  reviewedAt: string | null;
  riskId: string;
  status: string;
  title: string;
}

export interface SearchIndex {
  content: string | null;
  createdAt: string | null;
  entityId: string;
  entityType: string;
  id: string | null;
  title: string | null;
}

export interface SecurityPolicies {
  createdAt: string;
  id: string | null;
  policyBody: string;
  policyType: string;
  version: string;
}

export interface SessionHeartbeats {
  id: string | null;
  pingedAt: string;
  userId: string;
}

export interface SignalSaves {
  id: string | null;
  points: number | null;
  savedAt: string;
  title: string;
  url: string;
}

export interface SimTrades {
  amount: number | null;
  createdAt: string;
  fromUser: string;
  id: string | null;
  message: string | null;
  resolvedAt: string | null;
  status: string;
}

export interface SlaMetrics {
  createdAt: string;
  id: string | null;
  incidentsCount: number | null;
  metricPeriod: string;
  notes: string | null;
  responseP95Ms: number | null;
  responseP99Ms: number | null;
  slaMet: boolean | null;
}

export interface SloMetrics {
  badRequests: number;
  goodRequests: number;
  id: string | null;
  metricName: string;
  p50Ms: number | null;
  p95Ms: number | null;
  p99Ms: number | null;
  recordedAt: string;
  surface: string;
  totalRequests: number;
  windowEnd: string;
  windowStart: string;
}

export interface SocAlerts {
  alertId: string;
  assignedTo: string | null;
  createdAt: string;
  description: string | null;
  id: string | null;
  playbook: string | null;
  resolvedAt: string | null;
  severity: string;
  status: string;
  title: string;
}

export interface SocialBroadcasts {
  body: string | null;
  createdAt: string;
  id: string | null;
  userId: string | null;
}

export interface SocialConnections {
  connectedAt: string;
  handle: string | null;
  platform: string;
  userId: string | null;
}

export interface SovereignEvents {
  axisDelta: Record<string, any> | null;
  eventData: Record<string, any>;
  eventId: string;
  eventType: string;
  id: any | null;
  occurredAt: string;
}

export interface SovereignPointsLedger {
  createdAt: string;
  delta: number;
  id: string | null;
  note: string | null;
  reason: string;
  userId: string;
}

export interface TaskCompletions {
  axisType: string;
  completedAt: string | null;
  description: string | null;
  id: string | null;
  metadata: Record<string, any> | null;
  task: string | null;
  taskName: string | null;
  taskType: string;
}

export interface TelemetryEvents {
  createdAt: string;
  eventType: string;
  id: string | null;
  page: string | null;
  properties: Record<string, any> | null;
  sessionId: string | null;
}

export interface ThreatEvents {
  createdAt: string;
  detail: Record<string, any> | null;
  falsePositive: boolean | null;
  id: string | null;
  ipHash: string | null;
  notes: string | null;
  page: string | null;
  resolved: boolean | null;
  resolvedAt: string | null;
  sessionId: string | null;
  threatLevel: number;
  threatType: string;
  userAgent: string | null;
}

export interface TokenBalances {
  balance: number;
  updatedAt: string;
  userId: string;
}

export interface TokenCatalog {
  code: string | null;
}

export interface TravelJourneys {
  createdAt: string | null;
  destination: string;
  id: string | null;
  userId: string | null;
}

export interface Trophies {
  earnedAt: string | null;
  id: string | null;
  issuedAt: string | null;
  medalNum: number | null;
  trophyNum: number | null;
  userId: string | null;
}

export interface UserAssets {
  assetType: string | null;
  createdAt: string | null;
  id: string | null;
  name: string | null;
  quantity: number | null;
  trackName: string | null;
  userId: string | null;
}

export interface UserDedication {
  date: string;
  id: string | null;
  secondsToday: number;
  targetSeconds: number;
  updatedAt: string;
  userId: string | null;
}

export interface UserJourneys {
  actionsCount: number | null;
  completedTask: boolean | null;
  durationS: number | null;
  element: string | null;
  endedAt: string | null;
  entryPage: string | null;
  exitPage: string | null;
  id: string | null;
  pagesViewed: number | null;
  sessionId: string;
  sign: string | null;
  startedAt: string;
}

export interface WealthSnapshots {
  assetsJson: Record<string, any> | null;
  id: string | null;
  netWorth: number;
  note: string | null;
  snapshotAt: string;
}

export interface WorkflowDefinitions {
  createdAt: string;
  description: string | null;
  id: string | null;
  isActive: boolean | null;
  name: string;
  version: string | null;
  workflowId: string;
}

export interface WorkflowExecutions {
  durationMs: number | null;
  endedAt: string | null;
  errorMsg: string | null;
  id: string | null;
  input: Record<string, any> | null;
  instanceId: string;
  output: Record<string, any> | null;
  startedAt: string;
  status: string;
  stepsLog: Record<string, any> | null;
}

// ============================================================================
// RPC Function Types
// ============================================================================

export interface academy_promoteParams {
  stage: number;
  user: string;
}

export interface access_audit_logParams {
  limit: number;
}

export interface add_graph_relationshipParams {
  confidence: number;
  relationship_type: string;
  source_entity_id: string;
  source_system: string;
  strength: number;
  target_entity_id: string;
  user_id: string;
}

export interface advance_matrixParams {
  axis: string;
  track: number;
}

export interface apply_subscriptionParams {
  customer: string;
  period_end: string;
  period_start: string;
  status: string;
  tier: string;
  tier_num: number;
  uid: string;
}

export interface approve_memberParams {
  uid: string;
}

export interface authority_scoreParams {
  a: number;
  b: number;
  c: number;
}

export interface award_pointsParams {
  amount: number;
  note: string;
  reason: string;
  user: string;
}

export interface award_tokenParams {
  amount: number;
  token: string;
  user: string;
}

export interface check_trial_statusParams {
  default: any;
  uid: string;
}

export interface complete_taskParams {
  axis: string;
  axis_type: string;
  description: string;
  kind: string;
  points: number;
  task: string;
  task_name: string;
  task_type: string;
  title: string;
  weight: number;
}

export interface compute_authorityParams {
  a: number;
  b: number;
  c: number;
  is_owner: boolean;
}

export interface engagement_dayParams {
  at: string;
  default: any;
}

export interface engagement_reportParams {
  default: any;
  day: string;
}

export interface error_summaryParams {
  hours: number;
}

export interface evaluate_policyParams {
  context: Record<string, any>;
  policy_id: string;
}

export interface expire_trialParams {
  uid: string;
}

export interface extend_trialParams {
  seconds: number;
  uid: string;
}

export interface find_contradictionsParams {
  user_id: string;
}

export interface find_graph_pathsParams {
  max_depth: number;
  source_entity_id: string;
  target_entity_id: string;
  user_id: string;
}

export interface get_activity_feedParams {
  limit: number;
  offset: number;
}

export interface get_analytics_summaryParams {
  days: number;
}

export interface get_engagement_statusParams {
  default: any;
  uid: string;
}

export interface get_my_task_logParams {
  limit: number;
}

export interface get_platform_flagParams {
  key: string;
}

export interface get_threat_summaryParams {
  days: number;
}

export interface grant_permanent_accessParams {
  uid: string;
}

export interface grant_trial_accessParams {
  uid: string;
}

export interface graph_entity_centralityParams {
  user_id: string;
}

export interface has_active_accessParams {
  default: any;
  uid: string;
}

export interface lattice_nodeParams {
  a: number;
  b: number;
  c: number;
  phase: number;
  track: number;
}

export interface log_evolutionParams {
  axis: string;
  note: string;
}

export interface log_workflow_executionParams {
  duration_ms: number;
  instance_id: string;
  output: Record<string, any>;
  status: string;
  workflow_id: string;
}

export interface matrix_nodeParams {
  a: number;
  b: number;
  c: number;
}

export interface membership_reportParams {
  prices: Record<string, any>;
}

export interface milestones_for_axisParams {
  v: number;
}

export interface my_interest_profileParams {
  limit: number;
}

export interface notify_achievementParams {
  num: number;
  type: string;
}

export interface post_dispatchParams {
  body: string;
  category: string;
  title: string;
}

export interface propose_sim_tradeParams {
  amount: number;
  message: string;
  to: string;
}

export interface public_leaderboardParams {
  limit: number;
}

export interface published_dispatchesParams {
  limit: number;
}

export interface purchase_perkParams {
  perk_id: string;
}

export interface recall_ai_contextParams {
  limit: number;
}

export interface record_health_metricParams {
  good: number;
  p95_ms: number;
  surface: string;
  total: number;
}

export interface record_interest_signalParams {
  axis_type: string;
  content_id: string;
  content_type: string;
  signal_type: string;
  weight: number;
}

export interface record_sovereign_eventParams {
  axis_delta: Record<string, any>;
  event_data: Record<string, any>;
  event_type: string;
  idempotency: string;
}

export interface reject_memberParams {
  uid: string;
}

export interface report_client_errorParams {
  col: number;
  kind: string;
  line: number;
  message: string;
  page: string;
  source: string;
  stack: string;
  ua: string;
}

export interface resolve_sim_tradeParams {
  accept: boolean;
  trade_id: string;
}

export interface revoke_memberParams {
  uid: string;
}

export interface revoke_permanent_accessParams {
  uid: string;
}

export interface set_consult_statusParams {
  id: string;
  status: string;
}

export interface set_contract_statusParams {
  id: string;
  status: string;
}

export interface set_dispatch_publishedParams {
  id: string;
  pub: boolean;
}

export interface set_platform_flagParams {
  key: string;
  val: boolean;
}

export interface set_profile_visibilityParams {
  public: boolean;
}

export interface set_reservation_statusParams {
  id: string;
  status: string;
}

export interface submit_exam_resultParams {
  cert_name: string;
  exam_id: string;
  score: number;
  total: number;
}

export interface submit_feedbackParams {
  message: string;
  page: string;
  rating: number;
}

export interface track_for_signParams {
  sign: string;
}

export interface update_consentParams {
  granted: boolean;
  type: string;
  version: string;
}

export interface upsert_graph_entityParams {
  canonical_name: string;
  confidence: number;
  description: string;
  display_name: string;
  entity_type: string;
  metadata: Record<string, any>;
  source_system: string;
  user_id: string;
}

export interface zodiac_from_dateParams {
  d: string;
}

// ============================================================================
// Supabase Client Type
// ============================================================================

export interface Database {
  public: {
    Tables: {
      academy_access: AcademyAccess;
      academy_progress: AcademyProgress;
      access_audit: AccessAudit;
      access_grant_audit: AccessGrantAudit;
      activity_feed: ActivityFeed;
      advertisements: Advertisements;
      agent_threads: AgentThreads;
      ai_memory: AiMemory;
      api_keys: ApiKeys;
      automation_rules: AutomationRules;
      bloodline_nodes: BloodlineNodes;
      capability_kpi_log: CapabilityKpiLog;
      capability_registry: CapabilityRegistry;
      certificates: Certificates;
      character_records: CharacterRecords;
      circuit_breakers: CircuitBreakers;
      client_errors: ClientErrors;
      codex_bookmarks: CodexBookmarks;
      commission_contracts: CommissionContracts;
      consent_records: ConsentRecords;
      consult_requests: ConsultRequests;
      content_recommendations: ContentRecommendations;
      content_versions: ContentVersions;
      contribution_log: ContributionLog;
      conversations: Conversations;
      council_deliberations: CouncilDeliberations;
      daily_engagement: DailyEngagement;
      data_domains: DataDomains;
      data_entities: DataEntities;
      data_export_requests: DataExportRequests;
      data_lineage: DataLineage;
      dispatches: Dispatches;
      enterprise_accounts: EnterpriseAccounts;
      enterprise_audit: EnterpriseAudit;
      error_budget_policy: ErrorBudgetPolicy;
      ethics_declarations: EthicsDeclarations;
      event_rsvps: EventRsvps;
      evolution_events: EvolutionEvents;
      exam_results: ExamResults;
      expert_bookings: ExpertBookings;
      family_nodes: FamilyNodes;
      feature_flags: FeatureFlags;
      feedback: Feedback;
      focus_sessions: FocusSessions;
      governance_policies: GovernancePolicies;
      graph_entities: GraphEntities;
      graph_events: GraphEvents;
      graph_evidence: GraphEvidence;
      graph_relationships: GraphRelationships;
      habit_logs: HabitLogs;
      health_logs: HealthLogs;
      heritage_records: HeritageRecords;
      incidents: Incidents;
      interest_signals: InterestSignals;
      knowledge_edges: KnowledgeEdges;
      knowledge_nodes: KnowledgeNodes;
      leaderboard_snapshots: LeaderboardSnapshots;
      marketplace_listings: MarketplaceListings;
      matrix_progress: MatrixProgress;
      matrix_tracks: MatrixTracks;
      medals: Medals;
      media_items: MediaItems;
      media_reservations: MediaReservations;
      member_events: MemberEvents;
      member_perks: MemberPerks;
      member_posts: MemberPosts;
      member_presence: MemberPresence;
      messages: Messages;
      notifications: Notifications;
      oaths: Oaths;
      okr_key_results: OkrKeyResults;
      okr_objectives: OkrObjectives;
      platform_events: PlatformEvents;
      platform_metrics: PlatformMetrics;
      platform_owners: PlatformOwners;
      platform_settings: PlatformSettings;
      point_perks: PointPerks;
      policy_eval_log: PolicyEvalLog;
      policy_rules: PolicyRules;
      profiles: Profiles;
      publications: Publications;
      rate_limits: RateLimits;
      research_hypotheses: ResearchHypotheses;
      risk_register: RiskRegister;
      search_index: SearchIndex;
      security_policies: SecurityPolicies;
      session_heartbeats: SessionHeartbeats;
      signal_saves: SignalSaves;
      sim_trades: SimTrades;
      sla_metrics: SlaMetrics;
      slo_metrics: SloMetrics;
      soc_alerts: SocAlerts;
      social_broadcasts: SocialBroadcasts;
      social_connections: SocialConnections;
      sovereign_events: SovereignEvents;
      sovereign_points_ledger: SovereignPointsLedger;
      task_completions: TaskCompletions;
      telemetry_events: TelemetryEvents;
      threat_events: ThreatEvents;
      token_balances: TokenBalances;
      token_catalog: TokenCatalog;
      travel_journeys: TravelJourneys;
      trophies: Trophies;
      user_assets: UserAssets;
      user_dedication: UserDedication;
      user_journeys: UserJourneys;
      wealth_snapshots: WealthSnapshots;
      workflow_definitions: WorkflowDefinitions;
      workflow_executions: WorkflowExecutions;
    };
  };
}
