const fs=require('fs');
const assert=require('assert');
const migration=fs.readFileSync('supabase/migrations/20261005190000_omega_product_reality_read_models.sql','utf8');
const html=fs.readFileSync('life.html','utf8');
const reality=fs.readFileSync('omega-product-reality.js','utf8');
const life=fs.readFileSync('omega-life.js','utf8');
assert(migration.includes('omega_member_product_reality'));
assert(migration.includes('omega_platform_product_reality'));
assert(migration.includes('security_invoker = true'));
assert(migration.includes('omega_platform_events'));
assert(migration.includes('omega_member_mission_state'));
assert(migration.includes('knowledge_documents'));
assert(migration.includes('marketplace_orders'));
assert(migration.includes('stripe_webhook_events'));
assert(migration.includes('never synthetic activity'));
assert(html.includes('/omega-product-reality.js'));
assert(html.includes('product-reality-grid'));
assert(reality.includes('root.OmegaProductReality'));
assert(reality.includes("from(view)"));
assert(life.includes('OmegaProductReality.member'));
assert(life.includes('LIVE · OBSERVED'));
console.log('OMEGA_PRODUCT_REALITY=PASS');