const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const runtime = fs.readFileSync("omega-production-convergence.js", "utf8");
const context = { globalThis: {} };
vm.runInNewContext(runtime, context);
const api = context.globalThis.OmegaProductionConvergence;
assert.ok(api);
const openOwnerGate = api.evaluateGate({id:"credential_containment",priority:"P0",ownerAction:true,required:["provider_rotation_evidence","repository_history_scan","secret_lifecycle_record"],evidence:["repository_history_scan"]});
assert.equal(openOwnerGate.state,"UNVERIFIED");
assert.deepEqual(openOwnerGate.missingEvidence,["provider_rotation_evidence","secret_lifecycle_record"]);
const blockedRuntimeGate = api.evaluateGate({id:"commerce_reality",priority:"P0",ownerAction:false,required:["webhook_secret_configured","signature_verification","idempotency"],evidence:["signature_verification"],blockers:["payment provider is not production-proven"]});
assert.equal(blockedRuntimeGate.state,"BLOCKED");
assert.ok(blockedRuntimeGate.blockers.includes("payment provider is not production-proven"));
const allPass = api.evaluate({gates:[{id:"a",priority:"P0",ownerAction:false,required:["x"],evidence:["x"]},{id:"b",priority:"P1",ownerAction:false,required:["y"],evidence:["y"]}]});
assert.equal(allPass.state,"PASS");
assert.equal(allPass.productionAllowed,true);
const mixed = api.evaluate({gates:[{id:"a",priority:"P0",ownerAction:true,required:["x"],evidence:[]},{id:"b",priority:"P1",ownerAction:false,required:["y"],evidence:["y"]}]});
assert.equal(mixed.state,"UNVERIFIED");
assert.equal(mixed.productionAllowed,false);
assert.deepEqual(mixed.ownerActions,["a"]);
const hardBlock = api.evaluate({gates:[{id:"a",priority:"P0",ownerAction:false,required:["x"],evidence:[]}]});
assert.equal(hardBlock.state,"BLOCKED");
assert.equal(hardBlock.productionAllowed,false);
console.log("OMEGA_PRODUCTION_CONVERGENCE=PASS");
