[CmdletBinding()]
param([string]$RepositoryUrl='https://github.com/syd-omega-91717/sydomega-live',[string]$RunnerName='SYD-OMEGA-WIN',[string]$RunnerVersion='2.336.0',[string]$RunnerSha256='d59123a43003e357b0805b5d0f611d0bd2f65ab67d51bd070dd4e7a0f685c162')
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
$RunnerRoot='C:\actions-runner'; $Zip=Join-Path $RunnerRoot "actions-runner-win-x64-$RunnerVersion.zip"; $Config=Join-Path $RunnerRoot 'config.cmd'; $Run=Join-Path $RunnerRoot 'run.cmd'; $Api='https://api.github.com/repos/syd-omega-91717/sydomega-live/actions/runners/registration-token'; $Download="https://github.com/actions/runner/releases/download/v$RunnerVersion/actions-runner-win-x64-$RunnerVersion.zip"
if(-not(Test-Path $RunnerRoot)){New-Item -ItemType Directory -Path $RunnerRoot|Out-Null}; Set-Location $RunnerRoot
if(-not(Test-Path $Zip)){Invoke-WebRequest -Uri $Download -OutFile $Zip}; $Hash=(Get-FileHash $Zip -Algorithm SHA256).Hash.ToLowerInvariant(); if($Hash -ne $RunnerSha256.ToLowerInvariant()){throw "Runner SHA256 mismatch. Expected $RunnerSha256, got $Hash."}
if(-not(Test-Path $Config)-or-not(Test-Path $Run)){Add-Type -AssemblyName System.IO.Compression.FileSystem;[System.IO.Compression.ZipFile]::ExtractToDirectory($Zip,$RunnerRoot)}; if(-not(Test-Path $Config)-or-not(Test-Path $Run)){throw 'Runner package is incomplete.'}
$PatSecure=Read-Host 'Enter GitHub PAT with repository administration permission' -AsSecureString; $Ptr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($PatSecure); try{$Pat=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($Ptr)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($Ptr)}; if([string]::IsNullOrWhiteSpace($Pat)){throw 'GitHub PAT is required.'}
$Headers=@{Authorization="Bearer $Pat";Accept='application/vnd.github+json';'X-GitHub-Api-Version'='2022-11-28';'User-Agent'='syd-omega-runner-bootstrap'}; $RegistrationToken=(Invoke-RestMethod -Method Post -Uri $Api -Headers $Headers).token; if([string]::IsNullOrWhiteSpace($RegistrationToken)){throw 'GitHub returned no runner registration token.'}
Remove-Item '.\.runner','.\.credentials','.\.credentials_rsaparams' -Force -ErrorAction SilentlyContinue; & $Config --unattended --url $RepositoryUrl --token $RegistrationToken --name $RunnerName --labels 'self-hosted,Windows,X64,syd-omega' --work '_work'; if($LASTEXITCODE-ne0){throw "Runner registration failed with exit code $LASTEXITCODE."}; if(-not(Test-Path '.\.runner')-or-not(Test-Path '.\.credentials')){throw 'Runner registration did not create local credentials; refusing to start.'}; $Pat=$null;$RegistrationToken=$null;$Headers=$null; Write-Host 'REGISTERED: starting runner. Expect: Listening for Jobs' -ForegroundColor Green; & $Run; exit $LASTEXITCODE