#!/usr/bin/env python3
"""Static content-surface audit for every root HTML page.

This does not replace the runtime verifier. It checks the complete page estate
for structural/content regressions that a browser sweep can miss or that can
be masked by an approval gate: title, heading, main content, viewport, broken
placeholder language, and obviously unreadable micro-copy declarations.

It is intentionally diagnostic rather than destructive: it never rewrites a
page and it never invents content. Findings must be reviewed against the
page's capability state before a copy change is made.

Use --help to print this contract without scanning or modifying the repository.
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HTML_FILES = sorted(ROOT.glob("*.html"))
PLACEHOLDER = re.compile(r"\b(?:coming soon|placeholder|lorem ipsum|under construction|not implemented)\b", re.I)
UNBUILT = re.compile(r"\b(?:phase\s+\d+\s+feature\s+in\s+development|feature\s+in\s+development)\b", re.I)
MICROCOPY = re.compile(r"font-size\s*:\s*(\d+(?:\.\d+)?)px", re.I)


def strip_tags(value: str) -> str:
    return re.sub(r"<[^>]+>", " ", html.unescape(value))


def audit(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    findings: list[str] = []
    if not re.search(r"<meta[^>]+name=[\"']viewport[\"']", text, re.I):
        findings.append("missing viewport meta")
    if not re.search(r"<title>\s*[^<]+\s*</title>", text, re.I):
        findings.append("missing/empty title")
    if not re.search(r"<h1\b[^>]*>.*?</h1>", text, re.I | re.S):
        findings.append("missing h1")
    if not re.search(r"<main\b[^>]*>", text, re.I):
        findings.append("missing main")

    visible = strip_tags(text)
    if PLACEHOLDER.search(visible):
        findings.append("placeholder-language")
    if UNBUILT.search(visible):
        findings.append("explicit-unbuilt-state")

    for m in MICROCOPY.finditer(text):
        size = float(m.group(1))
        if size < 11:
            line = text[:m.start()].count("\n") + 1
            findings.append(f"micro-copy font-size {size:g}px at line {line}")
            break

    body = re.search(r"<body\b[^>]*>(.*?)</body>", text, re.I | re.S)
    if body:
        words = re.findall(r"[A-Za-z0-9Ω]{2,}", strip_tags(body.group(1)))
        if len(words) < 12 and path.name not in {"reset.html", "pending.html"}:
            findings.append(f"very-low-visible-copy ({len(words)} tokens)")
    return findings


def main() -> int:
    if any(arg in {"-h", "--help"} for arg in sys.argv[1:]):
        print(__doc__.strip())
        return 0

    total = len(HTML_FILES)
    findings: list[tuple[str, list[str]]] = []
    for path in HTML_FILES:
        f = audit(path)
        if f:
            findings.append((path.name, f))

    print(f"CONTENT SURFACE AUDIT: {total} root HTML pages scanned")
    print(f"Pages with findings: {len(findings)}")
    for name, items in findings:
        print(f"- {name}: {'; '.join(items)}")
    print("No content is auto-generated by this audit; every finding requires page/capability review.")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
