-- SYD OMEGA 91717 — notification write boundary
--
-- Notifications are generated by trusted SECURITY DEFINER server-side paths.
-- Explicitly deny direct client inserts so clients cannot forge system
-- notifications. SELECT remains governed by the existing RLS policy.

BEGIN;

REVOKE INSERT ON TABLE public.notifications FROM anon;
REVOKE INSERT ON TABLE public.notifications FROM authenticated;

COMMIT;
