-- SYD OMEGA 91717
-- Tighten remaining exposed SECURITY DEFINER execution boundaries.
begin;
revoke execute on function public._notify_approved() from public, anon, authenticated;
revoke execute on function public._notify_owner_member_approved() from public, anon, authenticated;
revoke execute on function public._notify_owner_member_rejected() from public, anon, authenticated;
revoke execute on function public.auto_soc_alert() from public, anon, authenticated;
revoke execute on function public.guard_profile_privileges() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.log_access_decision() from public, anon, authenticated;
revoke execute on function public.log_task_to_feed() from public, anon, authenticated;
revoke execute on function public.omega_auto_enable_rls() from public, anon, authenticated;
revoke execute on function public.add_graph_relationship(uuid,uuid,uuid,text,numeric,numeric,text) from public, anon, authenticated;
revoke execute on function public.upsert_graph_entity(uuid,text,text,text,text,jsonb,numeric,text) from public, anon, authenticated;
revoke execute on function public.apply_subscription_event(text,text,uuid,text,text,timestamptz,text) from public, anon, authenticated;
revoke execute on function public.apply_subscription_event(uuid,text,text,timestamptz,text,text,text) from public, anon, authenticated;
revoke execute on function public.log_evolution(text,text) from public, anon, authenticated;
revoke execute on function public.notify_member(uuid,text,text,jsonb) from public, anon, authenticated;
revoke execute on function public.omega_record_agent_operation(uuid,text,text,text,text,text,text,text) from public, anon, authenticated;
revoke execute on function public.queue_weekly_digest(uuid) from public, anon, authenticated;
revoke execute on function public.record_health_metric(text,bigint,bigint,integer) from public, anon, authenticated;
revoke execute on function public.send_weekly_digests() from public, anon, authenticated;
grant execute on function public.add_graph_relationship(uuid,uuid,uuid,text,numeric,numeric,text) to service_role;
grant execute on function public.upsert_graph_entity(uuid,text,text,text,text,jsonb,numeric,text) to service_role;
grant execute on function public.apply_subscription_event(text,text,uuid,text,text,timestamptz,text) to service_role;
grant execute on function public.apply_subscription_event(uuid,text,text,timestamptz,text,text,text) to service_role;
grant execute on function public.log_evolution(text,text) to service_role;
grant execute on function public.notify_member(uuid,text,text,jsonb) to service_role;
grant execute on function public.omega_record_agent_operation(uuid,text,text,text,text,text,text,text) to service_role;
grant execute on function public.queue_weekly_digest(uuid) to service_role;
grant execute on function public.record_health_metric(text,bigint,bigint,integer) to service_role;
grant execute on function public.send_weekly_digests() to service_role;
commit;
