-- Omega SYD OMEGA 91717
-- Backfills real source control for tables that have been live in this
-- project since before this repo's SQL history but were never declared in
-- ANY file here -- confirmed via scripts/audit.py check 7 ("never CREATE
-- TABLE'd/VIEW'd anywhere in supabase/") and matches GAP_ANALYSIS.md's own
-- standing note: "~83 tables live that this repo's SQL never created."
--
-- That was a tolerable, safe gap while these tables were unused (RLS on,
-- no client). It stops being tolerable the moment real code depends on
-- them, which courses.html now does -- without this file, restoring this
-- database from the repo's own migration history would be missing the
-- table entirely. Every column/type/default/FK below is copied from a live
-- information_schema.columns + pg_constraint query, not guessed.
--
-- CREATE TABLE IF NOT EXISTS is a no-op against the live database (the
-- tables already exist); this file exists for the next fresh database and
-- for anyone reading the schema who is not this session.

-- (2026-10-04) The DDL moved to 20260921010158_academy_courses_launch.sql,
-- which applies policies to these tables and runs first; a fresh
-- `supabase db reset` failed there. Live had both applied; no change there.
