create table if not exists public.omega_platform_events (id bigint generated by default as identity primary key, event_type text not null, route text, actor_user_id uuid references auth.users(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.omega_platform_events enable row level security;
create index if not exists omega_platform_events_created_at_idx on public.omega_platform_events(created_at desc);
create index if not exists omega_platform_events_actor_user_id_idx on public.omega_platform_events(actor_user_id);
create index if not exists omega_platform_events_event_type_idx on public.omega_platform_events(event_type);
create policy omega_platform_events_select_own on public.omega_platform_events for select to authenticated using (actor_user_id = auth.uid());
